"use client";

import React, { useState } from "react";
import { API_PATHS } from "../api/config"; // Adjust the path to your config file

const TransactionRent = () => {
  const [bookName, setBookName] = useState("");
  const [totalRent, setTotalRent] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setTotalRent(null);

    try {
      const response = await fetch(
        `${API_PATHS.TRANSACTIONS}/rent/${encodeURIComponent(bookName)}`
      );
      if (!response.ok) {
        throw new Error("Book not found or an error occurred");
      }

      const data = await response.json();
      setTotalRent(data.totalRent);
    } catch (err: unknown) {
      if (err instanceof Error) {
        setError(err.message);
      } else {
        setError("An unexpected error occurred.");
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">Total Rent Generated by Book</h1>

      <form onSubmit={handleSubmit} className="mb-6">
        <div className="flex items-center space-x-2">
          <input
            type="text"
            value={bookName}
            onChange={(e) => setBookName(e.target.value)}
            placeholder="Enter book name"
            className="flex-grow p-2 border border-gray-300 rounded"
            required
          />
          <button
            type="submit"
            className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
          >
            Get Total Rent
          </button>
        </div>
      </form>

      {loading && <p>Loading...</p>}

      {error && <p className="text-red-500">{error}</p>}

      {totalRent !== null && (
        <div className="mt-4 p-4 bg-green-100 border border-green-400 rounded">
          <h3 className="font-bold">Total Rent for &quot;{bookName}&quot;:</h3>
          <p>${totalRent}</p>
        </div>
      )}
    </div>
  );
};

export default TransactionRent;
